"""allow nullable

Revision ID: 03bf242abc85
Revises: a153b5f30c37
Create Date: 2021-12-16 11:49:58.656413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03bf242abc85'
down_revision = 'a153b5f30c37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('userid', sa.String(length=200), nullable=True))
    op.create_unique_constraint(None, 'Users', ['userid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Users', type_='unique')
    op.drop_column('Users', 'userid')
    # ### end Alembic commands ###
