"""Initial migration.

Revision ID: 9d0dc4ea1631
Revises: 
Create Date: 2021-12-14 17:56:52.907342

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d0dc4ea1631'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users_bot')
    op.drop_table('Users_demo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users_demo',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Users_demo_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('isadmin', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Users_demo_pkey'),
    sa.UniqueConstraint('email', name='Users_demo_email_key'),
    sa.UniqueConstraint('phone', name='Users_demo_phone_key')
    )
    op.create_table('Users_bot',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Users_bot_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Users_bot_pkey'),
    sa.UniqueConstraint('email', name='Users_bot_email_key')
    )
    # ### end Alembic commands ###
