"""changed password field to not unique

Revision ID: a153b5f30c37
Revises: a90d30634e60
Create Date: 2021-12-16 09:50:14.621719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a153b5f30c37'
down_revision = 'a90d30634e60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Users_password_key', 'Users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Users_password_key', 'Users', ['password'])
    # ### end Alembic commands ###
