from flask_sqlalchemy import model
from jwt import exceptions
from server.models import Destination, Order, Consignor, Customer, Users, Zone
from flask_session import Session
from flask import jsonify, g
import uuid
from werkzeug.security import generate_password_hash
import datetime
import time
from ..notification.email.send import sendEmail
from ...helper import randomGenerator


# ts stores the time in seconds
ts = time.time()

# print the current timestamp


def createOder(data, db):
    print('', g.userRole)
    id = uuid.uuid4()  # todo ........... to be return to the setter and getter

    customerid = data['customerid']
    consignerid = data['consignerid']

   # ..........................  get customer and consignor data...................................
    customerdata = Customer.query.filter_by(customerid=customerid).first()
    consignordata = Consignor.query.filter_by(consginerid=consignerid).first()

    customername = customerdata.fullname
    customerid = customerdata.customerid
    customernotes = data['custnote']
    consignername = consignordata.fullname
    consignerid = consignordata.consginerid
    pregion = Destination.query.filter_by(
        destinationid=data['destinationRegionData']).first().id
    # pdistrict = data['Packagedistdata']
    pstreet = data['packagestreet']
    pnotes = data['packagenotes']
    dregion = Destination.query.filter_by(
        destinationid=data['packageRegionData']).first().id
    # ddistrict = data['destinationData']
    dstreet = data['destinationstreet']
    dnotes = data['destinationnotes']
    consigneename = data['consigneename']
    consigneephone = data['consigneePhone']
    pickuptime = data['pickuptime']
    expdlrtime = data['expdlrtime']

    # date_time_obj = datetime.datetime.strptime(pickuptime, '%b %d %Y %I:%M%p')

    orderid = 'sga-'+str(pregion)+'-'+'-'+str(dregion)+str(ts).lower()
   #  check if user exists
    order = Order.query.filter_by(orderid=orderid).first()
    if not order:
        try:
            # print('Date:...........', date_time_obj)
            # print('Time:', date_time_obj.time())
            # print('Date-time:', date_time_obj)
            trackongNo = randomGenerator()

            neworder = Order(orderid=orderid,
                             customerid=customerid,
                             customername=customername,
                             trackingNo=trackongNo,
                             branchid=g.userBranchId,
                             customernotes=customernotes,
                             consignername=consignername,
                             consignerid=consignerid,
                             pregion=pregion,
                             pstreet=pstreet,
                             pnotes=pnotes,
                             dregion=dregion,
                             dstreet=dstreet,
                             dnotes=dnotes,
                             consigneename=consigneename,
                             pickuptime=pickuptime,
                             expdlrtime=expdlrtime)
            # ...................add()
            db.session.add(neworder)
            db.session.commit()

            user_email = Users.query.filter_by(
                branchId=neworder.branchid, role="Manager").first().email
            userlname = Users.query.filter_by(
                branchId=neworder.branchid, role="Manager").first().lname.upper()

            subject = "New Orders - Notification For : ", consignername.upper()

            packageDestination = Destination.query.filter_by(
                id=dregion).first()
            pickupLocation = Destination.query.filter_by(id=pregion).first()
            zonalDestination = Zone.query.filter_by(
                id=Destination.query.filter_by(id=pregion).first().zoneid)

            msg = "Greetings ", userlname, ",\n New Order has been created with the below details ..\n\nCustomer name: ", customername, "\nPickup Location: ", pickupLocation.upper(
            ), "\nDestionation: ", packageDestination.upper(), "(", zonalDestination, ")", "\nAnd Pickup time is: ", pickuptime, "\n\nRegards,\n\n--Sent by SGA-Courier AutoGenerated Notitication--"

            sendEmail(user_email, subject, msg)

            return jsonify({'message': 'Order created'}), 200

        except Exception as e:
            print(e)
            return jsonify({'message': 'Failed to create Order'}), 403
            pass
    return jsonify({'message': 'Order already exist'}), 409
